### ISSUE TITLE
Smart Hub issues

### ISSUE THREAD

**Issue by Olseda20** [fsherratt/ERL_SmartCities_2019#53]
I can't seem to figure out how to put/post successfully onto the smarthub I keep getting:
`JSON schema validation error processing 'type' in: 
[] 
Details: 
{
     "expected": "object", 
     "used": "null" 
} `

I don't really understand the interfacing. I used their example at the bottom of https://docs.google.com/document/d/1JZiO76uum4PD-ZSnvFgsyPBroWn036L5v-G-_o4XG-0/edit# but when I try to apply what I think is similar logic, to the episode 12 interfaces, I just get that error.

**Comment by Olseda20** [comment]
nvm got it

**Comment by fsherratt** [comment]
Duplicate of this https://github.com/fsherratt/ERL_SmartCities_2019/issues/7. Closing issue
